#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\ViewController::index
register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser